In [22]:
import numpy as np

# No.1

In [24]:
x = np.array([1,2,3]) # 1

# No.2

In [27]:
x.ndim  # 2

1

# No.3

In [43]:
x.size # 3

3

# No.4

In [30]:
x.itemsize # 4

4

# No.5

In [44]:
x.shape # 5

(3,)

# No.6

In [34]:
x1 = np.zeros((5,5)) # 6

In [35]:
x1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# No.7

In [36]:
x2 = np.ones(10) # 7

In [37]:
x2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# No.8

In [38]:
x2.reshape(2,5) #8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# No.9

In [45]:
x3=np.eye(3) # 9

In [42]:
x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# No.10

In [47]:
np.identity(5) # 10

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# No.11

In [54]:
x4 = np.linspace(0,24, 25) # 11

In [55]:
x4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

# No.12

In [56]:
x5=np.arange(10) # 12

In [58]:
x5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# No.13

In [59]:
x5.sum() # 13

45

In [63]:
x6=x5.reshape(2,5)

In [64]:
x6.sum(axis=0) # Sum across rows

array([ 5,  7,  9, 11, 13])

In [65]:
x6.sum(axis=-1) #  Sum across columns

array([10, 35])

In [66]:
x7= x4.reshape(5,5)

# No.14

In [68]:
x7.mean() # 14

12.0

# No.15

In [69]:
x7.std() # 15

7.211102550927978

# No.16

In [70]:
x7.ptp() # 16 Peak to peak difference

24.0

# No.17

In [71]:
x7.var() # 17 

52.0

# No.18

In [72]:
x7.min() # 18

0.0

# No.19

In [73]:
x7.max() # 19

24.0

# No.20

In [74]:
x7.argmax() # 20 index of max value

24

# No.21

In [75]:
x7.argmin() # 21 index of min value

0

# No.22

In [76]:
x7.any() # 22 . Returns true if any of the values in the array is true  

True

# No.23

In [77]:
x7.all() # 23. Returns true if all the values in the array is true

False

# No.24

In [78]:
x8=x7.copy() # 24 . Copy array

# No.25

In [89]:
np.diagonal(x7) # 25 . Gives the diagonal of the array

array([ 0.,  6., 12., 18., 24.])

In [90]:
np.diagonal(x7, -1) # Give lower diagonal i.e. one lower then teh central diagonal

array([ 5., 11., 17., 23.])

# No.26

In [103]:
x2.reshape(2,5).transpose() # 26 taking transpose i.e. converting (2,5) array to (5,2) array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [104]:
x8

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

# No.27

In [114]:
np.unravel_index(x8.argmax(), x8.shape) # 27 This will give the index of maximum value

(4, 4)

# No.28

In [285]:
np.random.rand(1) # 28 .This will give an random value based on standard uniform distribution

array([0.19846973])

# No.29

In [116]:
np.random.randn(5) # 29 This will give 5 randon number based on normal distribution

array([ 0.79111406,  0.09017277, -1.70923886, -0.61338975, -2.64554895])

# N0.30

In [131]:
np.random.randint(5,10, (2,3)) # 30.  This will give 2*3 matrix of randon integers between 5 and 10.

array([[5, 6, 6],
       [6, 7, 9]])

# No.31

In [136]:
x5[3:6]=[100,78,23]

In [137]:
x5

array([  0,   1,   2, 100,  78,  23,   6,   7,   8,   9])

In [142]:
x5.sort() # 31 . This will sort the array in  ascending order

In [143]:
x5

array([  0,   1,   2,   6,   7,   8,   9,  23,  78, 100])

# No.32

In [146]:
x7[0]=1

In [149]:
x7.prod() # 32 This will multiple all the elements in the array

2.585201673888498e+22

In [150]:
x7.prod(axis=0) # This will multiple across the row

array([15000., 22176., 31416., 43056., 57456.])

# No.33

In [152]:
 x9 =np.empty((2,2)) # 33 This will initialize an empty array of arbituray data

# No.34

In [155]:
np.empty_like(x8) # 34 This will initialize an empty array with the data and shape given as argument

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

# No. 35

In [156]:
np.logspace(2,4,5) # 35. This will generate logrithic array f size 4 between log2 and log4

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

# No.36

In [158]:
np.ones_like(x7) # 36 This will give the ones arrays of the same size of the given array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# No.37

In [162]:
np.zeros_like(x6)  # 37 This will give the zeros arrays of the same size of the given array as an aurgument

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# No.38

In [165]:
x8.dtype # 38 This will give the type of the array

dtype('float64')

In [167]:
x8

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

# No.39

In [170]:
x10 = x8.astype("int32") # 39 . This will change the type of the array from float to integer

In [171]:
x10.dtype

dtype('int32')

# No.40

In [175]:
x6

array([[  0,   1,   2,   6,   7],
       [  8,   9,  23,  78, 100]])

In [174]:
x6.shape

(2, 5)

In [177]:
x6.ndim

2

In [186]:
x11 = np.atleast_3d(x6) # 40 This will convert the given array to 3d array

In [187]:
x11

array([[[  0],
        [  1],
        [  2],
        [  6],
        [  7]],

       [[  8],
        [  9],
        [ 23],
        [ 78],
        [100]]])

# No.41

In [197]:
x7_1=np.mat(x7) # 41. This converts a given array to a matrix

In [201]:
type(x7_1)

numpy.matrix

In [202]:
type(x7)

numpy.ndarray

# No.42

In [204]:
x7_2, x7_3, x7_4, x7_5, x7_8 =np.array_split(x7,5) # Thsi will split teh array as per the give argument

In [205]:
x7_2

array([[1., 1., 1., 1., 1.]])

# No.43

In [213]:
np.concatenate((x7,x7_2), axis=0 ) # 43 . This will concatenate the two arrays together i.e. a new row will be appended

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [215]:
np.concatenate((x7,x7_2.T), axis=1 ) # . This will concatenate the two arrays together i.e. a new column will be appended

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 5.,  6.,  7.,  8.,  9.,  1.],
       [10., 11., 12., 13., 14.,  1.],
       [15., 16., 17., 18., 19.,  1.],
       [20., 21., 22., 23., 24.,  1.]])

In [217]:
np.concatenate((x7,x7), axis=-1 ) # . This will concatenate the two arrays together i.e. a new column will be appended

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 5.,  6.,  7.,  8.,  9.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 20., 21., 22., 23., 24.]])

# No.44

In [233]:
x6_1=np.full((2,5), 101) # 44. This will create a array of give shape and with value given in the argument

In [230]:
x6

array([[  0,   1,   2,   6,   7],
       [  8,   9,  23,  78, 100]])

# No.45

In [231]:
x6.shape

(2, 5)

In [237]:
x6

array([[  0,   1,   2,   6,   7],
       [  8,   9,  23,  78, 100]])

In [235]:
x6_1.shape

(2, 5)

In [238]:
x6_1

array([[101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101]])

In [236]:
np.hstack((x6,x6_1)) # 45. This will concatenate the two arrays horizentolly. i.e new columns are appended

array([[  0,   1,   2,   6,   7, 101, 101, 101, 101, 101],
       [  8,   9,  23,  78, 100, 101, 101, 101, 101, 101]])

# No.46

In [240]:
np.vstack((x6,x6_1)) # 46. This will contatenate the two arrage vertically i.e. new rows are appended

array([[  0,   1,   2,   6,   7],
       [  8,   9,  23,  78, 100],
       [101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101]])

# No.47

In [242]:
x6.shape

(2, 5)

In [243]:
x6_1.shape

(2, 5)

In [244]:
np.dot(x6,x6_1.T) # 47. This is matrix multiplation and the shape of the resultant array will be 2x2.

array([[ 1616,  1616],
       [22018, 22018]])

In [245]:
x7

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [248]:
x7_5.T.shape

(5, 1)

In [249]:
np.dot(x7,x7_1.T)

matrix([[   5.,   35.,   60.,   85.,  110.],
        [  35.,  255.,  430.,  605.,  780.],
        [  60.,  430.,  730., 1030., 1330.],
        [  85.,  605., 1030., 1455., 1880.],
        [ 110.,  780., 1330., 1880., 2430.]])

# No.48

In [265]:
x7[1:-1,1:-1].fill(101) # 48 This fill the scale value into an existing array

In [266]:
x7

array([[  1.,   1.,   1.,   1.,   1.],
       [  5., 101., 101., 101.,   9.],
       [ 10., 101., 101., 101.,  14.],
       [ 15., 101., 101., 101.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])

# No.49

In [268]:
x8

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [270]:
np.compress([0,0,1],x8, axis=0) # 49. This will give 3rd row since only 2nd index in the condition is true

array([[10., 11., 12., 13., 14.]])

In [272]:
np.compress([False,False,False, True], x8, axis =1) # This will give 4th column

array([[ 3.],
       [ 8.],
       [13.],
       [18.],
       [23.]])

# No.50

In [283]:
x7

array([[  1.,   1.,   1.,   1.,   1.],
       [  5., 101., 101., 101.,   9.],
       [ 10., 101., 101., 101.,  14.],
       [ 15., 101., 101., 101.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])

In [281]:
condition = (x7 > 15) & (x7 <24)

In [284]:
np.extract(condition, x7) # 50. This will extract the values from the array based on the condition

array([19., 20., 21., 22., 23.])